### ISSUE TITLE
Mixas ESC issues

### ISSUE THREAD

**Issue by Avysuarez** [PX4/sapog#33]
@dagar 
I have issues with the Mixas  ESC, I already followed all instruction by @mhkabir for the configuration of the ESC, the assignment and the rotation of motors it's right and the copter doesn't fly, only flips on the takeoff. This is the configuration of the ESC #1 
<img width="283" alt="esc1 1" src="https://user-images.githubusercontent.com/12182176/48496718-7dde9180-e7e7-11e8-8891-f8f3c7d761af.PNG">
<img width="314" alt="esc1 2" src="https://user-images.githubusercontent.com/12182176/48496731-8767f980-e7e7-11e8-9605-8d9b333a7d9d.PNG">
The other ESC have the same configuration only change the assignment on the esc_index the ESC#2 =1, ESC#3=2 and ESC#4=3. 
What could be wrong?

**Comment by mhkabir** [comment]
Myxas are not running Sapog. What ESCs do you exactly have?

**Comment by Avysuarez** [comment]
Mixas

**Comment by Tony3dr** [comment]
@RomanBapst

**Comment by Avysuarez** [comment]
This is a video of what it does during the takeoff. Ther throttle only respond in the stabilized mode.
https://www.youtube.com/watch?v=DRjNlU9GyF0

**Comment by pavel-kirienko** [comment]
@Avysuarez according to the screenshot posted above, Myxas are configured in the RPM control mode, but the RPM PID controller is not tuned (I see the default settings, which are quite conservative and are not suitable for flying). You should read the quick-start guide you've been referred to earlier; specifically, look at the section [Using Myxa in multirotor aircraft](https://forum.zubax.com/t/quick-start-guide-for-myxa-v0-1/911/7?u=pavel-kirienko). Currently, we recommend using the voltage control mode for multirotors; to use it, set the configuration parameter `uavcan.rcm` or `rcpwm.ctl_mode` (depending on which interface you're using now) to 2.

I am closing this ticket because it has no relation to Sapog. If you have any further questions about Myxa, please, consider posting them at forum.zubax.com. Thanks!
